spring:
  application:
    name: csddd-service
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8083


logging:
  level:
    com.nsmm.esg.csddd_service.controller: DEBUG